const SKILLS = [
  "Critical thinking",
  "Communication skills",
  "Creativity",
  "Problem solving",
  "Perseverance",
  "Collaboration",
  "Information literacy",
  "Technology skills and digital literacy",
  "Media literacy",
  "Global awareness",
  "Self-direction",
  "Social skills",
  "Literacy skills",
  "Civic literacy",
  "Social responsibility",
  "Innovation skills",
  "Thinking skills",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science & Analytics",
  "Data Engineering",
  "Data Visualization",
  "Network and Information Security (Cybersecurity)",
  "Cloud Computing/AWS",
  "Extended Reality (Virtual Reality and Augmented Reality)",
  "Internet of Things (IoT)",
  "UI/UX Design",
  "Mobile Development",
  "Blockchain",
  "Quantum Computing",
  "Robotics",
  "Product Management",
  "Salesforce/CRMs",
  "Low-Code Platforms",
  "Javascript",
  "Python",
  "Go",
  "Java",
  "Kotlin",
  "PHP",
  "C#",
  "Swift",
  "R",
  "Ruby",
  "C and C++",
  "Matlab",
  "TypeScript",
  "Scala",
  "React",
  "Vue",
  "Bootstrap",
  "Ember",
  "Angular",
  "Django",
  "Ruby on Rails",
  "Express",
  "Spring",
  "ASP.Net",
  "Core",
];

export default SKILLS;
